# Generated by Django 5.0.6 on 2024-06-30 13:25

from django.db import migrations, models

#автоматически созданная модель для БД
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userText', models.TextField()),
                ('dateText', models.DateTimeField()),
            ],
        ),
    ]
